[workspace]
resolver = "2"

members = [
    "daemon", "cli", "shared"]

[workspace.dependencies]
bincode = "1.3.3"
toml = "0.8.10"

[workspace.dependencies.serde]
version = "1.0.197"
features = ["derive", "serde_derive"]
